data_ingestion:
  type: 'sklearn_internal'
  csv:
    location: 'stud.csv'
  sklearn_internal:
    name: 'breast_cancer'
    categorical_columns: ['']

problem:
  type: 'classification'

data_transformation:
  test_size: 0.2
  target: 'target'